// <auto-generated />
namespace John_Doe_Food_Ltd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TestSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "202012141016555_TestSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
